# Generated by Django 4.2 on 2023-04-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_student_user_is_teacher_user_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='qr_id',
        ),
    ]
