# Generated by Django 4.2 on 2023-04-15 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_user_id_user_qr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qr_id',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('qr_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_id', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points_balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
