# Generated by Django 4.2 on 2023-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.IntegerField(default=10),
        ),
    ]
