# Generated by Django 4.2 on 2023-04-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_inventory_alter_products_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='availability status'),
        ),
    ]
