# Generated by Django 4.2 on 2023-04-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_inventory_alter_products_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
